global using MassTransit;
global using MindfulTime.AI.Domain.Interfaces;
global using MindfulTime.AI.Domain.Models;
global using Newtonsoft.Json;
global using OpenClasses.Machine;
global using OpenClasses.Weather;
global using Microsoft.AspNetCore.Mvc;
global using MindfulTime.AI.Domain.Services;
global using System.Reflection;